
	#' Takes an action that affects a mobile device.
	#'
	#' For example, remotely wiping a device. Autogenerated via \code{\link[googlePackageMaker]{package_make}}.
	#'
	#' @seealso \href{https://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.device.mobile
	#' \item https://www.googleapis.com/auth/admin.directory.device.mobile.action
	#' }
	#' @param customerId The unique ID for the customer's Google Workspace account. As an account administrator, you can also use the `my_customer` alias to represent your account's `customerId`. The `customerId` is also returned as part of the [Users resource](/admin-sdk/directory/v1/reference/users).
	#' @param resourceId The unique ID the API service uses to identify the mobile device.
	#' @param action The action to be performed on the device.
	#' @param callback JSONP
	#' @param fields Selector specifying which fields to include in a partial response.
	#' @param uploadType Legacy upload protocol for media (e.g. "media", "multipart").
	#' @param upload_protocol Upload protocol for media (e.g. "raw", "multipart").
	#' @param prettyPrint Returns response with indentations and line breaks.
	#' @param quotaUser Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
	#' @param alt Data format for response.
	#' @param gargle_token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(...) with appropriate scopes. See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_request Whether to return the request without making it. Defaults to FALSE. See \code{\link[gargle]{request_build}} for more info on the returned request object.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	mobiledevices.action <- function(customerId, resourceId, action = NULL, callback = NULL, fields = NULL, uploadType = NULL, upload_protocol = NULL, prettyPrint = NULL, quotaUser = NULL, alt = NULL, gargle_token = gargle::token_fetch(scopes = .endpoints[['directory.mobiledevices.action']]$scopes[[1]]), return_request = F, return_response = F){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('return_request', 'return_response', 'gargle_token')]
		req <- gargle::request_develop(endpoint = .endpoints[['directory.mobiledevices.action']], params = params, base_url = 'https://admin.googleapis.com/')
		req <- gargle::request_build(method = req$method, path = req$path, params = req$params, body = req$body, token = httr::config(token = gargle_token), base_url = req$base_url)
		if(return_request) return(req)
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Removes a mobile device.
	#'
	#'  Autogenerated via \code{\link[googlePackageMaker]{package_make}}.
	#'
	#' @seealso \href{https://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.device.mobile
	#' }
	#' @param customerId The unique ID for the customer's Google Workspace account. As an account administrator, you can also use the `my_customer` alias to represent your account's `customerId`. The `customerId` is also returned as part of the [Users resource](/admin-sdk/directory/v1/reference/users).
	#' @param resourceId The unique ID the API service uses to identify the mobile device.
	#' @param callback JSONP
	#' @param fields Selector specifying which fields to include in a partial response.
	#' @param uploadType Legacy upload protocol for media (e.g. "media", "multipart").
	#' @param upload_protocol Upload protocol for media (e.g. "raw", "multipart").
	#' @param prettyPrint Returns response with indentations and line breaks.
	#' @param quotaUser Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
	#' @param alt Data format for response.
	#' @param gargle_token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(...) with appropriate scopes. See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_request Whether to return the request without making it. Defaults to FALSE. See \code{\link[gargle]{request_build}} for more info on the returned request object.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	mobiledevices.delete <- function(customerId, resourceId, callback = NULL, fields = NULL, uploadType = NULL, upload_protocol = NULL, prettyPrint = NULL, quotaUser = NULL, alt = NULL, gargle_token = gargle::token_fetch(scopes = .endpoints[['directory.mobiledevices.delete']]$scopes[[1]]), return_request = F, return_response = F){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('return_request', 'return_response', 'gargle_token')]
		req <- gargle::request_develop(endpoint = .endpoints[['directory.mobiledevices.delete']], params = params, base_url = 'https://admin.googleapis.com/')
		req <- gargle::request_build(method = req$method, path = req$path, params = req$params, body = req$body, token = httr::config(token = gargle_token), base_url = req$base_url)
		if(return_request) return(req)
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Retrieves a mobile device's properties.
	#'
	#'  Autogenerated via \code{\link[googlePackageMaker]{package_make}}.
	#'
	#' @seealso \href{https://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.device.mobile
	#' \item https://www.googleapis.com/auth/admin.directory.device.mobile.action
	#' \item https://www.googleapis.com/auth/admin.directory.device.mobile.readonly
	#' }
	#' @param customerId The unique ID for the customer's Google Workspace account. As an account administrator, you can also use the `my_customer` alias to represent your account's `customerId`. The `customerId` is also returned as part of the [Users resource](/admin-sdk/directory/v1/reference/users).
	#' @param resourceId The unique ID the API service uses to identify the mobile device.
	#' @param projection Restrict information returned to a set of selected fields.
	#' @param callback JSONP
	#' @param fields Selector specifying which fields to include in a partial response.
	#' @param uploadType Legacy upload protocol for media (e.g. "media", "multipart").
	#' @param upload_protocol Upload protocol for media (e.g. "raw", "multipart").
	#' @param prettyPrint Returns response with indentations and line breaks.
	#' @param quotaUser Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
	#' @param alt Data format for response.
	#' @param gargle_token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(...) with appropriate scopes. See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_request Whether to return the request without making it. Defaults to FALSE. See \code{\link[gargle]{request_build}} for more info on the returned request object.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	mobiledevices.get <- function(customerId, resourceId, projection = NULL, callback = NULL, fields = NULL, uploadType = NULL, upload_protocol = NULL, prettyPrint = NULL, quotaUser = NULL, alt = NULL, gargle_token = gargle::token_fetch(scopes = .endpoints[['directory.mobiledevices.get']]$scopes[[1]]), return_request = F, return_response = F){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('return_request', 'return_response', 'gargle_token')]
		req <- gargle::request_develop(endpoint = .endpoints[['directory.mobiledevices.get']], params = params, base_url = 'https://admin.googleapis.com/')
		req <- gargle::request_build(method = req$method, path = req$path, params = req$params, body = req$body, token = httr::config(token = gargle_token), base_url = req$base_url)
		if(return_request) return(req)
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Retrieves a paginated list of all mobile devices for an account.
	#'
	#'  Autogenerated via \code{\link[googlePackageMaker]{package_make}}.
	#'
	#' @seealso \href{https://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.device.mobile
	#' \item https://www.googleapis.com/auth/admin.directory.device.mobile.action
	#' \item https://www.googleapis.com/auth/admin.directory.device.mobile.readonly
	#' }
	#' @param customerId The unique ID for the customer's Google Workspace account. As an account administrator, you can also use the `my_customer` alias to represent your account's `customerId`. The `customerId` is also returned as part of the [Users resource](/admin-sdk/directory/v1/reference/users).
	#' @param query Search string in the format given at https://developers.google.com/admin-sdk/directory/v1/search-operators
	#' @param orderBy Device property to use for sorting results.
	#' @param pageToken Token to specify next page in the list
	#' @param projection Restrict information returned to a set of selected fields.
	#' @param sortOrder Whether to return results in ascending or descending order. Must be used with the `orderBy` parameter.
	#' @param maxResults Maximum number of results to return. Max allowed value is 100.
	#' @param callback JSONP
	#' @param fields Selector specifying which fields to include in a partial response.
	#' @param uploadType Legacy upload protocol for media (e.g. "media", "multipart").
	#' @param upload_protocol Upload protocol for media (e.g. "raw", "multipart").
	#' @param prettyPrint Returns response with indentations and line breaks.
	#' @param quotaUser Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
	#' @param alt Data format for response.
	#' @param gargle_token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(...) with appropriate scopes. See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_request Whether to return the request without making it. Defaults to FALSE. See \code{\link[gargle]{request_build}} for more info on the returned request object.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	mobiledevices.list <- function(customerId, query = NULL, orderBy = NULL, pageToken = NULL, projection = NULL, sortOrder = NULL, maxResults = NULL, callback = NULL, fields = NULL, uploadType = NULL, upload_protocol = NULL, prettyPrint = NULL, quotaUser = NULL, alt = NULL, gargle_token = gargle::token_fetch(scopes = .endpoints[['directory.mobiledevices.list']]$scopes[[1]]), return_request = F, return_response = F){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('return_request', 'return_response', 'gargle_token')]
		req <- gargle::request_develop(endpoint = .endpoints[['directory.mobiledevices.list']], params = params, base_url = 'https://admin.googleapis.com/')
		req <- gargle::request_build(method = req$method, path = req$path, params = req$params, body = req$body, token = httr::config(token = gargle_token), base_url = req$base_url)
		if(return_request) return(req)
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}
